services:
  voice-ai:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    ports:
      - "3000:3000"   # Next.js frontend
      - "5001:5001"   # Whisper service
    environment:
      - NODE_ENV=production
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - WHISPER_MODEL=${WHISPER_MODEL:-small}
    volumes:
      - ./tmp:/app/tmp  # For temporary audio files
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health", "&&", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s 