version: '3.8'

services:
  # Next.js Frontend Application
  nextjs-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: local-voice-ai-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OLLAMA_BASE_URL=http://ollama-service:11434
      - OLLAMA_MODEL=gemma3:1b
      - WHISPER_SERVICE_URL=http://whisper-service:5001
      - WHISPER_MODEL=tiny
    networks:
      - voice-ai-network
    volumes:
      - ./app/tmp:/app/tmp
    restart: unless-stopped

    image: ollama/ollama:latest
    container_name: local-voice-ai-ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_MODELS=/ollama/models
    volumes:
      - ollama-storage:/ollama
    networks:
      - voice-ai-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: >
      sh -c "
      ollama serve &
      sleep 15 &&
      ollama pull gemma3:1b &&
      wait
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

networks:
  voice-ai-network:
    driver: bridge

volumes:
  # Persistent volume for Hugging Face cache (Whisper models)
  hf-cache:
    driver: local

  # Persistent volume for Ollama models
  ollama-storage:
    driver: local
