version: '3.8'

services:
  # Next.js Frontend Application
  nextjs-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: local-voice-ai-frontend
    network_mode: host
    environment:
      - NODE_ENV=production
      - OLLAMA_BASE_URL=http://localhost:8000/llm
      - OLLAMA_MODEL=gemma3:12b
      - WHISPER_SERVICE_URL=http://localhost:8000/stt
      - TTS_SERVICE_URL=http://localhost:8000/tts
      - TTS_API_KEY=${TTS_API_KEY}
    volumes:
      - ./app/tmp:/app/tmp
    restart: unless-stopped


volumes:
  # Persistent volume for Hugging Face cache (Whisper models)
  hf-cache:
    driver: local

  # Persistent volume for Ollama models
  ollama-storage:
    driver: local
