---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
  labels:
    app: nextjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
        - name: nextjs-app
          image: gcr.io/ai-test-465504/local-voice-ai:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: OLLAMA_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: voice-ai-config
                  key: OLLAMA_BASE_URL
            - name: OLLAMA_MODEL
              valueFrom:
                configMapKeyRef:
                  name: voice-ai-config
                  key: OLLAMA_MODEL
            - name: NODE_ENV
              value: "production"
            - name: WHISPER_SERVICE_URL
              value: "http://whisper-service:5001"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
          volumeMounts:
            - name: tmp-volume
              mountPath: /app/tmp
      volumes:
        - name: tmp-volume
          emptyDir: {}
