apiVersion: apps/v1
kind: Deployment
metadata:
  name: breezyvoice
  labels:
    app: breezyvoice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: breezyvoice
  template:
    metadata:
      labels:
        app: breezyvoice
    spec:
      containers:
      - name: breezyvoice
        image: breezyvoice:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "api.py"]
        ports:
        - containerPort: 8080
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 60
        volumeMounts:
        - name: hf-cache
          mountPath: /root/.cache/huggingface
      volumes:
      - name: hf-cache
        persistentVolumeClaim:
          claimName: hf-cache-pvc 