---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voice-ai-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /api/whisper
            pathType: Prefix
            backend:
              service:
                name: whisper-service
                port:
                  number: 5001
          - path: /api/breezy
            pathType: Prefix
            backend:
              service:
                name: breezyvoice-service
                port:
                  number: 8999
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextjs-app
                port:
                  number: 3000
