# NextJS 應用 Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voice-ai-ingress-nextjs
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "voice-ai-nextjs-ip"
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: nextjs-app
                port:
                  number: 3000

# Ollama 服務 Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voice-ai-ingress-ollama
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "voice-ai-ollama-ip"
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: ollama-service
                port:
                  number: 11434

# Whisper 服務 Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voice-ai-ingress-whisper
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "voice-ai-whisper-ip"
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: whisper-service
                port:
                  number: 5001